name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: Build, Scan and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install Node Modules
        run: npm install

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      - name: File System Scan
        run: trivy fs .

      - name: Build Docker Image
        run: |
          docker build -t candycrushgithubaction .

      - name: Tag Docker Image
        run: |
          docker tag candycrushgithubaction ramkiprabhu28/candycrushgithubaction:latest

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push ramkiprabhu28/candycrushgithubaction:latest

      - name: Image Scan
        run: |
          trivy image ramkiprabhu28/candycrushgithubaction:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: |
          docker pull ramkiprabhu28/candycrushgithubaction:latest

      - name: Scan Docker Image
        run: |
          trivy image ramkiprabhu28/candycrushgithubaction:latest

      - name: Stop Existing Container
        run: |
          docker stop candycrush || true
          docker rm candycrush || true

      - name: Deploy Container
        run: |
          docker run -d \
            --name candycrush \
            -p 3000:3000 \
            ramkiprabhu28/candycrushgithubaction:latest
      # Configure Eks cluster
      - name: Update kubeconfig
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
          kubectl get nodes
      # Deploy Eks cluster
      - name: Deploy to EKS
        run: |
         pwd
         ls
         kubectl apply -f "candycrush/github actions/deployment-service.yml"
        
